apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: sauravbiswas/multi-worker
      ports:
        - containerPort: 9999
      imagePullPolicy: Always



# Getting created pods
# kubectl get pods