apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050 # Port using which other pods can communicate with the target pod
      targetPort: 3000 # Port of the targeted pod
      nodePort: 31515 # Port that is opened up to the outside world
  selector:
    component: web